# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import uuid
import base64
import pyperclip as pc
from PyQt5.QtWidgets import QMessageBox
import os
from typing import Text
from PyQt5.QtCore import Qt
import time


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.build_btn = QtWidgets.QPushButton(self.centralwidget)
        self.build_btn.setGeometry(QtCore.QRect(60, 340, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.build_btn.setFont(font)
        self.build_btn.setObjectName("build_btn")
        self.build_btn.clicked.connect(self.clicke)


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 170, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")


        self.licence_in = QtWidgets.QLineEdit(self.centralwidget)
        self.licence_in.setGeometry(QtCore.QRect(60, 100, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.licence_in.setFont(font)
        self.licence_in.setObjectName("licence_in")

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(60, 260, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password_maker"))
        self.build_btn.setText(_translate("MainWindow", "BUILD"))
        self.label.setText(_translate("MainWindow", "Password:"))
        self.label2.setText(_translate("MainWindow", " "))
    
    def clicke(self):
        if not self.licence_in.text() == "" :
            message = self.licence_in.text()
            message_bytes = message.encode('ascii')
            base64_bytes = base64.b64encode(message_bytes)
            base64_message = base64_bytes.decode('ascii')
            self.label2.setText(base64_message)
            pc.copy(base64_message)
            msg = QMessageBox()
            msg.setWindowTitle("COPIED")
            msg.setText("the licence Copied")
            x = msg.exec_()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("ERORR")
            msg.setText("The INPUT box is empty")
            x = msg.exec_()

if __name__ == "__main__":
    app= QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
